docs: describe your change...
ngrx/platform pull request #2729
Opened 2020-10-02 16:29 UTC by oscar-stokkup

its worth a calling out in the configuration section -> Custom Router State Serialization, docs should mention to add the router state to the state.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently documentation is missing to add router to state when you do a Custom Router State Serialization

Closes #

## What is the new behavior?
Added new example under the "In your root reducer"

## Does this PR introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Other information

2020-10-02 17:05 UTC, timdeschryver approved these changes

2020-10-02 18:20 UTC, alex-okrushko requested changes

2020-10-02 18:20 UTC, alex-okrushko commented on projects/ngrx.io/content/guide/router-store/configuration.md
> +  router: RouterReducerState<any>;
```suggestion
  router: RouterReducerState&lt;any&gt;;
```

2020-10-03 16:28 UTC, alex-okrushko approved these changes
Thank you!

2020-10-07 19:58 UTC, merged