docs: add labeler
ngrx/platform pull request #2878
Opened 2021-01-12 19:20 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[X] Other... Please describe: Add support for the labeler. It's improve readability of the scopes affected by the PR.
```

## What is the current behavior?

Closes #1939

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

2021-01-14 20:28 UTC, timdeschryver requested changes

2021-01-14 20:28 UTC, timdeschryver commented on .github/.labeler.yml
> +  - projets/ngrx.io/*
Can you fix the typo `projets` to `projects` please?
Here, and also the other occurrences.

2021-01-18 06:56 UTC, timdeschryver reviewed
Sorry that I didn't see this the fist time but could you also rename the files to just `labeler` (without the dot) please?

2021-01-18 13:54 UTC, timdeschryver approved these changes

2021-01-18 15:52 UTC, brandonroberts approved these changes

2021-01-18 15:53 UTC, merged

2021-01-18 15:53 UTC, brandonroberts commented
Thanks @va-stefanek!