chore(all): update ts-snippet to 5.0.2
ngrx/platform pull request #3062
Opened 2021-07-02 01:30 UTC by david-shortman

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: package update and related fixes
```

## What is the current behavior?

ts-snippet has been updated with new features like outputting the actual error produced when using `toFail`.

## What is the new behavior?

ts-snippet is updated to v5.0.2.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

`toInfer` now implies `toSucceed`, and some of the tests using `toInfer` actually had failures in them.

2021-07-02 01:30 UTC, david-shortman commented
😅 The type tests were driving me crazy and it turns out ts-snippet is a little more powerful now which would have been nice to know earlier...

2021-07-02 21:58 UTC, markostanimirovic requested changes

2021-07-02 21:58 UTC, markostanimirovic commented on modules/store/spec/types/feature_creator.spec.ts
> +              entities,
```suggestion
              books: entities,
```

or switch `entities` with `books` (line 152)

2021-07-07 14:21 UTC, markostanimirovic approved these changes

2021-07-07 16:33 UTC, timdeschryver approved these changes

2021-07-07 16:34 UTC, merged

2021-07-07 16:34 UTC, timdeschryver commented
Thanks @david-shortman