docs(store): add feature creator guide
ngrx/platform pull request #3202
Opened 2021-10-25 17:29 UTC by markostanimirovic

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

Closes #3183

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2021-10-30 01:42 UTC, brandonroberts requested changes

2021-10-30 01:42 UTC, brandonroberts commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +## What is NgRx feature?
```suggestion
## What is an NgRx feature?
```

2021-10-30 01:42 UTC, brandonroberts commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +const {
```suggestion
export const {
```

2021-10-30 15:47 UTC, timdeschryver commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +and selectors for obtaining slices of the feature state. Also, we need to define a feature name needed to register
I find this easier to read:

```suggestion
and selectors to obtain slices of the feature state. Also, we need to define a feature name needed to register
```

2021-10-30 15:47 UTC, timdeschryver commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +the feature reducer in the NgRx store. Therefore, we can consider the NgRx feature as a group of feature name,
```suggestion
the feature reducer in the NgRx store. Therefore, we can consider the NgRx feature as a grouping of the feature name,
```

2021-10-30 15:47 UTC, timdeschryver commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +// `createFeature` is imported from `@ngrx/store` package
```suggestion
```

2021-10-30 15:47 UTC, timdeschryver commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +Generated selectors can be used independently or to create other selectors:
```suggestion
The generated selectors can be used independently or to create other selectors:
```

2021-10-30 15:47 UTC, timdeschryver commented on projects/ngrx.io/content/guide/store/feature-creators.md
> +Registering the feature reducer in the store can be done by passing the entire feature object to the `StoreModule.forFeature` method:
What about adding a header here?
```suggestion
## Feature Registration 

Registering the feature reducer in the store can be done by passing the entire feature object to the `StoreModule.forFeature` method:
```

2021-11-02 07:49 UTC, timdeschryver approved these changes

2021-11-02 10:53 UTC, brandonroberts approved these changes

2021-11-02 10:53 UTC, merged