docs(migration): breaking change with mock store teardown
ngrx/platform pull request #3294
Opened 2022-01-19 08:35 UTC by daniel-sc

see #3264

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-01-20 22:45 UTC, brandonroberts requested changes

2022-01-20 22:45 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v13.md
> +jasmine.getEnv().afterEach(() => {
Add the import here also

```suggestion
import { MockStore } from '@ngrx/store/testing';

jasmine.getEnv().afterEach(() => {
```

2022-01-20 22:45 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v13.md
> +When using jasmine, you can reset the mock store after each test by adding the following to your `test.ts`:
```suggestion
When using Jasmine, reset the mock store after each test by adding the following to the `test.ts`:
```

2022-01-21 11:41 UTC, timdeschryver requested changes
I'm rejecting this to prevent a merge.
I want to try a workaround (I got an idea based on this PR) locally so this wouldn't be an issue anymore.

2022-01-21 17:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v13.md
> +  TestBed.inject(MockStore, null)?.resetSelectors();
```suggestion
  TestBed.inject(MockStore)?.resetSelectors();
```
```suggestion
  TestBed.inject(MockStore, null)?.resetSelectors();
```

2022-01-21 17:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v13.md
> +Mock stores are not reset automagically after each test.
I think adding a "why note" can help to clear things up.


```suggestion
Mock stores are not reset automagically after each test. 

Note that this only applicable when the Angular `TestBed` isn't teared down by Angular, for more info see the [ModuleTeardownOptions options](https://angular.io/api/core/testing/ModuleTeardownOptions).
```

2022-01-21 17:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v13.md
> +```
Let's also add a jest example:

```suggestion
```ts
import { MockStore } from '@ngrx/store/testing';

jasmine.getEnv().afterEach(() => {
  TestBed.inject(MockStore, null)?.resetSelectors();
});
```

When using Jest, reset the mock store after each test by using a `afterEach` hook:

```ts
import { MockStore } from '@ngrx/store/testing';

afterEach(() => {
  TestBed.inject(MockStore)?.resetSelectors();
});
```
```

2022-01-21 17:49 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v13.md
> +```
The suggestions are action weird, the following can be appended:

```ts
import { MockStore } from '@ngrx/store/testing';

afterEach(() => {
  TestBed.inject(MockStore)?.resetSelectors();
});
```

2022-01-22 19:13 UTC, timdeschryver approved these changes

2022-01-27 20:23 UTC, brandonroberts approved these changes

2022-01-27 20:24 UTC, merged

2022-01-27 20:24 UTC, brandonroberts commented
Thanks @daniel-sc!