refactor: Replaced deprecated observable$.subscribe usages
ngrx/platform pull request #3314
Opened 2022-02-11 06:42 UTC by wiksien

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

2022-02-11 12:53 UTC, markostanimirovic requested changes
Thanks for the PR @wiksien!

1. Run `yarn install` to install dependencies.
2. When committing changes, don't add the `--no-verify` flag to make sure the changed code is properly formatted.

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/effects/entity-cache-effects.spec.ts
> +    }, fail});
```ts
effects.saveEntities$.subscribe({
  next: (result) => {
    expect(result).toEqual(completion);
    done();
  },
  error: fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/effects/entity-cache-effects.spec.ts
> +    }, done.fail});
```ts
effects.saveEntities$.subscribe({
  next: (result) => {
    expect(result instanceof SaveEntitiesSuccess).toBe(false);
    expect(result instanceof SaveEntitiesCanceled).toBe(true); // instead
    done();
  },
  error: done.fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/effects/entity-cache-effects.spec.ts
> +    }, done.fail});
```ts
effects.saveEntities$.subscribe({
  next: (result) => {
    expect(result instanceof SaveEntitiesSuccess).toBe(true);
    done();
  },
  error: done.fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/effects/entity-cache-effects.spec.ts
> +    }, done.fail});
```ts
effects.saveEntities$.subscribe({
  next: (result) => {
    expect(result instanceof SaveEntitiesSuccess).toBe(true);
    expect(dataService.saveEntities).not.toHaveBeenCalled();
    done();
  },
  error: done.fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-data.module.spec.ts
> +        .subscribe({(act) => actions.push(act)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-data.module.spec.ts
> +      actions$.pipe(skip(1)).subscribe({(act) => actions.push(act)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-data.module.spec.ts
> +      cacheSelector$.subscribe({(cache) => {
```ts
cacheSelector$.subscribe({
  next: (cache) => {
    try {
      expect(cache.Hero.entities[1]).toEqual(data.Hero[1]);
      expect(cache.Villain.entities[30]).toEqual(data.Villain[0]);
      expect(metaReducerLog.join('|')).toContain(TEST_ACTION);
      done();
    } catch (error: any) {
      fail(error);
    }
  },
  error: fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        }});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.getAll().subscribe({expectDataToBe(heroes, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.getAll().subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.getByKey(1).subscribe({expectDataToBe(hero, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(heroes, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.load().subscribe({expectDataToBe(heroes, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.load().subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      });
```ts
heroCollectionService.getAll(options).subscribe({
  next: (data) => fail('should not have data but got data'),
  error: (error) => {
    expect(error instanceof PersistanceCanceled).toBe(true);
    expect(error.message).toBe('Test cancel');
    done();
  },
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      }, fail});
```ts
heroCollectionService.getAll(options).subscribe({
  next: (data) => {
    expect(data).toEqual(heroes);
    done();
  },
  error: fail,
});
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({(data) => expect(data).toEqual(heroes), fail});
```suggestion
        .subscribe({
          next: (data) => expect(data).toEqual(heroes),
          error: fail,
        });
```

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(hero, done, undefined, extra)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.add(hero).subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(42, done, undefined, extra)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      });
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(1, done, undefined, extra)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      heroCollectionService.delete(42).subscribe({expectErrorToBe(error, done)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(update, done, undefined, extra)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({expectDataToBe(postUpdate, done, undefined, extra)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      successActions$.pipe(delay(1)).subscribe({(act) => {
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +        .subscribe({(data) => expect(data).toEqual(hero1)});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +      }});
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +    });
revert this change

2022-02-11 12:53 UTC, markostanimirovic commented on modules/data/spec/entity-services/entity-collection-service.spec.ts
> +    }});
revert this change

2022-02-14 22:49 UTC, wiksien commented
Sorry for causing problems with fixing this issue. I hope it is all okay now, thank you for being such a big help.

2022-02-16 11:40 UTC, brandonroberts approved these changes

2022-02-16 11:41 UTC, merged