style(example-app): fix lint warning
ngrx/platform pull request #3323
Opened 2022-02-18 17:42 UTC by cedricduffournet

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-02-18 17:51 UTC, markostanimirovic requested changes
Some of the unused arguments can be removed 👇

2022-02-18 18:08 UTC, timdeschryver commented on projects/example-app/src/app/core/reducers/layout.reducer.ts
> +  on(AuthActions.logoutConfirmation, (_state) => ({ showSidenav: false }))
Both can result in a State shape that is different from the "official" state.
To enforce the correctness of the returned state, we should explicitly add the return type.

For more info 👇 
https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/on-function-explicit-return-type.md

2022-02-18 18:11 UTC, cedricduffournet commented on projects/example-app/src/app/core/reducers/layout.reducer.ts
> +  on(AuthActions.logoutConfirmation, (_state) => ({ showSidenav: false }))
Yes, I see. For now I removed it.
Should we apply eslint-plugin-ngrx rules to example-app project ? It could be nice

2022-02-18 18:15 UTC, markostanimirovic approved these changes

2022-02-19 18:49 UTC, timdeschryver approved these changes

2022-02-19 18:49 UTC, merged

2022-02-19 18:49 UTC, timdeschryver commented
Thanks once again @cedricduffournet