docs: few tweaks to the migration guide
ngrx/platform pull request #3649
Opened 2022-11-05 19:09 UTC by timdeschryver

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3615

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

Added titles 
Added some extra info
Reworded a few things

2022-11-05 19:10 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v15.md
> +#### Title
Introduced in #3648

2022-11-05 19:11 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v15.md
> +The projector is strict by default, but can be bypassed with an `any` type assertion to specify a less specific type.
Updated the description because we didn't implement the `any` type generic

2022-11-06 01:24 UTC, brandonroberts requested changes

2022-11-06 01:24 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v15.md
> +The `ReactiveComponentModule` is removed in favor of [`LetModule`](https://ngrx.io/api/component/LetModule) and [`PushModule`](https://ngrx.io/api/component/PushModule).
These shouldn't include the domain 

```suggestion
The `ReactiveComponentModule` is removed in favor of [`LetModule`](/api/component/LetModule) and [`PushModule`](/api/component/PushModule).
```

2022-11-06 12:32 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v15.md
> -`provideEffects` expected the effects to be passed as an array.
This is removed because #3638 re-allows this to keep the signatures the same for EffectsModule and provideEffects

2022-11-06 12:32 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v15.md
> +The `ReactiveComponentModule` is removed in favor of [`LetModule`](https://ngrx.io/api/component/LetModule) and [`PushModule`](https://ngrx.io/api/component/PushModule).
Oh, good catch - Thanks Brandon!

2022-11-06 12:33 UTC, timdeschryver commented on projects/ngrx.io/content/guide/migration/v15.md
> +The `@Effect` decorator is removed in favor of [`createEffect`](https://ngrx.io/api/effects/createEffect).
```suggestion
The `@Effect` decorator is removed in favor of [`createEffect`](api/effects/createEffect).
```

2022-11-06 22:20 UTC, brandonroberts approved these changes

2022-11-06 22:27 UTC, markostanimirovic approved these changes

2022-11-06 22:28 UTC, merged