build(docs-app): update dependencies to latest Angular 15 version
ngrx/platform pull request #3680
Opened 2022-11-29 23:23 UTC by cedricduffournet

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2022-11-30 01:20 UTC, cedricduffournet commented
close/open to restart CI

2022-11-30 17:39 UTC, timdeschryver requested changes
Some changes (colors) we need to look at 

![image](https://user-images.githubusercontent.com/28659384/204868880-fce17fd6-c97d-48db-9926-3399a1ac85ef.png)

![image](https://user-images.githubusercontent.com/28659384/204868988-3b557089-2eb3-43b5-8c36-2fc8a5573865.png)

![image](https://user-images.githubusercontent.com/28659384/204869156-03b9c1d9-73f1-4a69-96e1-5eda74691892.png)

2022-11-30 17:45 UTC, cedricduffournet commented on projects/ngrx.io/src/styles/2-modules/_code.scss
> +@use '@angular/material' as mat;
No I did it manually

2022-11-30 17:46 UTC, cedricduffournet commented
thanks @timdeschryver I'll check that

2022-12-01 09:13 UTC, cedricduffournet commented
@timdeschryver I restore textarea height and fix hamburger button pres. 
It seems that automatic labelling is not working today

2022-12-02 03:43 UTC, brandonroberts approved these changes

2022-12-02 03:44 UTC, merged