docs(component-store): update docs to add dictionnary of obs inside select
ngrx/platform pull request #3730
Opened 2022-12-28 08:54 UTC by tomalaforge

add explanation about the new signature of select to accept a dictionnary of obs to create a view model

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3704 

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-12-30 14:59 UTC, brandonroberts requested changes

2022-12-30 14:59 UTC, brandonroberts commented on projects/ngrx.io/content/guide/component-store/read.md
> +The `select` method accepts a dictionnary of observables as input and return an observable of dictionnary as output. View models can be written the following way:
```suggestion
The `select` method accepts a dictionary of observables as input and returns an observable of the dictionary of values as output. View models can be written the following way: 
```

2022-12-30 14:59 UTC, brandonroberts commented on projects/ngrx.io/content/guide/component-store/read.md
> +  });
```suggestion
  private readonly vm$ = this.select({
    movies: this.movies$,
    userPreferredMovieIds: this.userPreferredMovieIds$,
    userPreferredMovies: this.userPreferredMovies$
  });
```

2022-12-30 14:59 UTC, brandonroberts commented on projects/ngrx.io/content/guide/component-store/read.md
> +  },{debounce: true}, // 👈 setting this selector to debounce
```suggestion
  private readonly fetchMoviesData$ = this.select({
    moviesPerPage: this.moviesPerPage$,
    currentPageIndex: this.currentPageIndex$
  },{debounce: true}, // 👈 setting this selector to debounce
```

2023-01-02 10:34 UTC, tomalaforge commented on projects/ngrx.io/content/guide/component-store/read.md
> +  });
well seen

2023-01-02 17:31 UTC, timdeschryver commented on projects/ngrx.io/content/guide/component-store/read.md
> +The `select` method accepts a dictionary of observables as input and returns an observable of the dictionary of values as output. View models can be written the following way:
```suggestion
The `select` method accepts a dictionary of observables as input and returns an observable of the dictionary of values as output. View models can be written in the following way: 
```

2023-01-03 15:50 UTC, timdeschryver approved these changes
Thanks @tomalaforge

2023-01-06 13:38 UTC, brandonroberts approved these changes

2023-01-06 13:38 UTC, merged