docs(example): update the effects docs
ngrx/platform pull request #3779
Opened 2023-02-18 00:15 UTC by JeromeWirth

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Updates the mergeMap operator to exhaustMap within the effects docs to make a more realistic example with best practices.

Closes #3770

2023-02-18 00:58 UTC, brandonroberts requested changes

2023-02-18 00:58 UTC, brandonroberts commented on projects/ngrx.io/content/guide/effects/index.md
> +Effects are built on top of observable streams provided by RxJS. Effects are listeners of observable streams that continue until an error or completion occurs. In order for effects to continue runnin
```suggestion
Effects are built on top of observable streams provided by RxJS. Effects are listeners of observable streams that continue until an error or completion occurs. In order for effects to continue running in the event of an error in the observable, or completion of the observable stream, they must be nested within a "flattening" operator, such as `exhaustMap`, `concatMap`, `mergeMap` and other flattening operators. The example below shows the `loadMovies$` effect handling errors when fetching movies.
```

2023-02-18 11:19 UTC, timdeschryver approved these changes

2023-02-26 21:36 UTC, markostanimirovic approved these changes

2023-02-27 13:07 UTC, merged