docs(entity): add recipe for entity adapters with extra selectors
ngrx/platform pull request #3912
Opened 2023-05-28 22:15 UTC by danielglejzner

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

New recipe file for entity adapters with extra selectors

Closes #3800 

## What is the new behavior?
New recipe file for entity adapters with extra selectors

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

2023-05-29 13:59 UTC, markostanimirovic requested changes
Thanks Daniel! I like the order on this page. Few suggestions regarding the examples 👇 

The text should be also adapted according to updated examples.

2023-05-29 13:59 UTC, markostanimirovic commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapters-with-extra-selectors.md
> +</code-example>
```suggestion
<code-example header="user-list.component.ts">

import { usersFeature } from './users.state';

@Component({ /* ... */ })
export class UserListComponent{
	private readonly store = inject(Store);

  readonly users$ = this.store.select(usersFeature.selectAll);
	readonly isUserSelected$ = this.store.select(usersFeature.selectIsUserSelected);
  readonly selectedUser$ = this.store.select(usersFeature.selectSelectedUser);
}

</code-example>
```

2023-05-29 14:46 UTC, DanielSofomo commented
Great suggestions @markostanimirovic - updated :)

2023-05-29 14:49 UTC, danielglejzner commented
Great suggestions @markostanimirovic - updated :)

2023-05-29 15:31 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapters-with-extra-selectors.md
> +# Using Entity Adapters with Extra Selectors
👍

2023-05-29 15:48 UTC, timdeschryver reviewed
What about a "putting it all together" section where the code snippets are all shown within a single file, which makes it easy to copy paste?
Or, we we can also create the file first and insert comments that include a number to reference it later and provide more info/context.

2023-05-29 15:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +This example demonstrates a User state management using NgRx Store with `Entity Adapters` and `Extra Selectors` for a feature.
Thoughts? It's mainly to add links to the adapter and selector docs.

```suggestion
This recipe demonstrates how to combine [entity adapter](/guide/entity/adapter#entity-adapter) (selectors) within [extraSelectors](/guide/store/feature-creators#providing-extra-selectors).
As an example, let's look at some code from a User state management feature.
```

2023-05-29 15:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +Then use the `createReducer` function from NgRx to create a reducer for the `User` feature.
```suggestion
Then use the `createReducer` function to create a reducer for the `User` feature.

```

2023-05-29 15:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +Then create the `User` feature using the `createFeature` function. This will generate all basic selectors automatically, and we can specify extra selectors using the `extraSelectors` option.
```suggestion
Then create the `User` feature using the `createFeature` function. 
This generates all the basic selectors automatically, and we can specify extra selectors using the `extraSelectors` option.

```

2023-05-29 15:48 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +In the component, we `inject` the `Store` service from NgRx and select the data we need from the state using the selectors generated by the `createFeature` function.
```suggestion
To use the selector within a component, `inject` the `Store` and select the data from the state using the selectors generated by the `createFeature` function.

```

2023-05-29 15:48 UTC, timdeschryver reviewed
What about a "putting it all together" section where the code snippets are all shown within a single file, which makes it easy to copy paste?
Or, we we can also create the file first and insert comments that include a number to reference it later and provide more info/context.

2023-05-30 13:26 UTC, markostanimirovic commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +const reducer = createReducer(
We can also add an empty line between imports and reducer. The rest of the code snippets look great! :)

```suggestion
import { UserListPageActions } from './user-list-page.actions';

const reducer = createReducer(

```

2023-05-30 14:14 UTC, timdeschryver commented on projects/ngrx.io/content/guide/entity/recipes/entity-adapter-with-feature-creator.md
> +In the component, we `inject` the `Store` service from NgRx and select the data we need from the state using the selectors generated by the `createFeature` function.
Rewording this provide a smoother transition on what the next snippet does.

2023-05-31 01:32 UTC, danielglejzner commented
Pushed a batch of changes based on your suggestions :) - ready for re-review.

2023-05-31 11:25 UTC, timdeschryver approved these changes
Thanks! 🤩

2023-05-31 17:42 UTC, merged