feat(component-store): added custom equal option in select
ngrx/platform pull request #3933
Opened 2023-06-19 14:42 UTC by rosostolato

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`select` uses `distinctUntilChanged` but there was no way to provide a custom equality fn.

Closes #3931

## What is the new behavior?
Added `equal` option to provide a custom equality function for `distinctUntilChanged` in `select` method.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2023-06-20 17:25 UTC, timdeschryver approved these changes
LGTM. just a little nit

2023-06-20 20:01 UTC, markostanimirovic requested changes

2023-06-20 20:01 UTC, markostanimirovic commented on modules/component-store/src/component-store.ts
> +  const defaultEqualityFn: ValueEqualityFn<unknown> = (previous, current) =>
```suggestion
  const defaultEqualityFn: ValueEqualityFn<Result> = (previous, current) =>
```

2023-06-20 21:31 UTC, rosostolato commented on modules/component-store/spec/component-store.spec.ts
> +  describe('selector with custom equal fn', () => {
I kind of followed the same implementation of `{ debounce: true }`, so I added them just to make sure that adding a custom `equal` function won't break the basics. But you're right, we should drop and just keep the equality check one.

2023-06-21 13:14 UTC, markostanimirovic reviewed
Thanks @rosostolato! The code and tests look good to me. A small suggestion for docs:

2023-06-21 13:14 UTC, markostanimirovic commented on projects/ngrx.io/content/guide/component-store/read.md
> +Select uses `distinctUntilChanged` by default, which means that it will emit a new value only if the value has changed. It's possible to override the equality comparer by passing a custom comparer fu
```suggestion
## Using a custom equality function

The observable created by the `select` method compares the newly emitted value with the previous one using the default equality check (`===`) and emits only if the value has changed. However, the default behavior can be overridden by passing a custom equality function to the `select` method config.
```

2023-06-21 13:14 UTC, markostanimirovic commented on projects/ngrx.io/content/guide/component-store/read.md
> +    {equal: (prev, curr) => prev.length === curr.length} // 👈 custom equality comparer
```suggestion
    {equal: (prev, curr) => prev.length === curr.length} // 👈 custom equality function
```

2023-06-21 16:09 UTC, timdeschryver commented on modules/component-store/src/component-store.ts
> +export interface SelectConfig<T> {
Good catch 👍

2023-06-21 17:41 UTC, rosostolato commented
Those were great feedback! Thank you, guys!

2023-06-21 22:45 UTC, markostanimirovic approved these changes
LGTM 👍 Thanks @rosostolato!

2023-06-21 23:18 UTC, brandonroberts approved these changes

2023-06-21 23:18 UTC, brandonroberts commented
Nice work!

2023-06-21 23:18 UTC, merged