Update prefer-concat-latest-from.md
ngrx/platform pull request #3938
Opened 2023-06-29 16:17 UTC by cgbrucezjy

since this is the new official eslint-plugin for ngrx we need to add @ in front of the rule name

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ X ] No
```

## Other information

2023-07-01 14:20 UTC, timdeschryver requested changes
Good catch!
Would you also like to update the other pages please?

- https://github.com/ngrx/platform/blob/4298ef7f7213fd8fea6527ec315238b8e2786e4f/projects/ngrx.io/content/guide/eslint-plugin/rules/use-consistent-global-store-name.md
- https://github.com/ngrx/platform/blob/4298ef7f7213fd8fea6527ec315238b8e2786e4f/projects/ngrx.io/content/guide/eslint-plugin/rules/select-style.md

2023-07-01 14:20 UTC, timdeschryver commented on projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md
> +"plugins": ["@ngrx/eslint-plugin"]
Let's keep this snippet just to be the config settings.

```suggestion
  "@ngrx/prefer-concat-latest-from": ["warn", { "strict": true }]
}
```

2023-07-01 14:20 UTC, timdeschryver commented on projects/ngrx.io/content/guide/eslint-plugin/rules/prefer-concat-latest-from.md
> +"plugins": ["@ngrx/eslint-plugin"]
Same here.

```suggestion
  "@ngrx/prefer-concat-latest-from": ["warn", { "strict": false }]
}
```

2023-07-03 15:55 UTC, cgbrucezjy commented
> Good catch! Would you also like to update the other pages please?
> 
> * https://github.com/ngrx/platform/blob/4298ef7f7213fd8fea6527ec315238b8e2786e4f/projects/ngrx.io/content/guide/eslint-plugin/rules/use-consistent-global-store-name.md
> * https://github.com/ngrx/platform/blob/4298ef7f7213fd8fea6527ec315238b8e2786e4f/projects/ngrx.io/content/guide/eslint-plugin/rules/select-style.md

updated

2023-07-05 15:35 UTC, cgbrucezjy commented
@timdeschryver circle ci has some weird failure, im not able to merge

2023-07-05 15:41 UTC, brandonroberts approved these changes

2023-07-05 15:41 UTC, merged