fix(eslint): fix avoid-dispatching-multiple-actions-sequentially rule to detect inject (#3943)
ngrx/platform pull request #3949
Opened 2023-07-07 22:19 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, the eslint plugin does not detect the actions and state, if it is injected via the new inject method

Related to #3948

Closes #3948 

## What is the new behavior?

Updated actions detection logic to also check for actions injected via inject method from the @angular/core package

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

2023-07-10 19:46 UTC, timdeschryver requested changes

2023-07-10 19:46 UTC, timdeschryver commented on modules/eslint-plugin/spec/rules/avoid-dispatching-multiple-actions-sequentially.spec.ts
> +  // https://github.com/timdeschryver/eslint-plugin-ngrx/issues/86
```suggestion
```

2023-07-10 19:46 UTC, timdeschryver commented on modules/eslint-plugin/spec/rules/avoid-dispatching-multiple-actions-sequentially.spec.ts
> +  // https://github.com/ngrx/platform/issues/3513
```suggestion
```

2023-07-10 19:46 UTC, timdeschryver commented on modules/eslint-plugin/spec/rules/avoid-dispatching-multiple-actions-sequentially.spec.ts
> +  // https://github.com/ngrx/platform/issues/3513
```suggestion
```

2023-07-17 10:22 UTC, timdeschryver approved these changes

2023-07-17 22:06 UTC, markostanimirovic approved these changes

2023-07-17 22:06 UTC, merged