fix(store-devtools): reduce CD cycles by listening `message` outside of Angular
ngrx/platform pull request #3970
Opened 2023-07-24 12:24 UTC by arturovt

This commit updates the extension connection setup and wraps it with `runOutsideAngular` to prevent running change detection too frequently. This ensures that change detection is only triggered when all asynchronous actions have been processed.

Closes #3839

2023-07-24 15:03 UTC, timdeschryver requested changes
It seems like with this change importing an existing state throws an error.
This should be resolved first, or this should be added to the docs.

```txt
reducer.ts:75  ERROR Error: Action '[Auth/API] Login Redirect' running outside NgZone. https://ngrx.io/guide/store/configuration/runtime-checks#strictactionwithinngzone
    at inNgZoneAssert_reducer.ts:11:13
    at serialization_reducer.ts:24:23
    at immutability_reducer.ts:11:23
    at utils.ts:139:14
    at computeNextEntry (reducer.ts:72:17)
    at recomputeStates (reducer.ts:122:9)
    at reducer.ts:533:24
    at StoreDevtools.liftedStateSubscription.liftedAction$.pipe.state (devtools.ts:96:38)
    at scanInternals.js:14:21
    at OperatorSubscriber._this._next (OperatorSubscriber.js:33:21)
handleError @ core.mjs:10072
computeNextEntry @ reducer.ts:75
recomputeStates @ reducer.ts:122
(anonymous) @ reducer.ts:533
StoreDev
[state.txt](https://github.com/ngrx/platform/files/12147295/state.txt)
tools.liftedStateSubscription.liftedAction$.pipe.state @ devtools.ts:96
```

You can reproduce this by running the example app and importing my export.

```cmd
npx nx serve example-app
```

2023-07-24 15:17 UTC, arturovt commented
@timdeschryver thanks for checking, I haven't imported the state and haven't checked that case, I'll have a look. It actually should keep functioning seamlessly w/o breaking changes, so I'd fix it.

2023-07-27 12:50 UTC, arturovt commented
@timdeschryver I'll post my thoughts aloud so we can discuss the concerns which I think about:

- this change may cause breaking issues in unit tests that implicitly depend on a specific number and sequence of change detections to pass their assertions. However, I am not sure if someone is unit testing the Redux plugin, which is available only in the browser. This means that we might eliminate the reason for this to be a breaking change.
- the `DevtoolsExtension` (which has the `createChangesObservable` method) is not exposed publicly to end users through the NgRx API, which means I'm not sure if someone would explicitly subscribe to `createChangesObservable` and be affected by the fact that subscriber events would be coming from outside the Angular zone.
- the `StoreDevtool` are exposed publicly. Its public properties, which may be read by end users, are `liftedState` and `state`. The `state` basically pipes the `liftedState`. The `liftedState` is obtained from `liftedStateSubject.asObservable()`, where `liftedStateSubject` always calls its `next` within the Angular zone, since we call `enterNgZone()` previously.

Wdyt?

2023-07-27 14:41 UTC, timdeschryver commented
@arturovt thanks for the elaborate answer.

- I would assume no projects are using devtools to unit test their components (I don't think this will break e2e tests)
- I also assume no projects are interacting with the devtools within their "user code".

The question was more about if this change could break existing application because the result of this change is that it won't trigger the CD as much as before.
But, that's probably not the case, since most of the apps turn devtools off in production.

The other thing I was thinking about are applications that don't rely on NgZone.

2023-07-27 15:13 UTC, arturovt commented
Apps which have the NgZone noopped won’t be affected since NgZone class is substituted with NoopNgZone which does nothing (just invokes callbacks directly).

2023-07-27 15:26 UTC, brandonroberts commented
I do think that there is a possibility of this being an unexpected change in behavior from those who are including the Devtools in production, which I know there are cases of this out there.

That being said, we always recommend not doing this, so we could be covered in that case.

2023-07-27 15:37 UTC, brandonroberts commented
> 

I don't think that's necessary, but we could add that to the docs to be more clear. The other option would be to have this behind a flag, such as:

```ts
provideStoreDevtools({
  ngZone: 'enabled' | 'noop'
});
```

And have it default to `enabled` for now, and you can change it to `noop`. In the future, we flip it to `noop` by default.

2023-07-27 15:44 UTC, timdeschryver commented
I like that suggestion @brandonroberts 👍

2023-07-27 15:44 UTC, arturovt commented
Alright, so I should re-work the changes and add a new config property?

2023-07-27 19:31 UTC, brandonroberts approved these changes

2023-07-28 02:30 UTC, markostanimirovic commented on modules/store-devtools/src/devtools.ts
> +}
```suggestion
/**
 * If the devtools extension is connected out of the Angular zone,
 * this operator will emit all events within the zone.
 */
function emitInZone<T>(zoneConfig: ZoneConfig): MonoTypeOperatorFunction<T> {
  if (zoneConfig.connectInZone) {
    return (source) => source;
  }

  const { ngZone } = zoneConfig;

  return (source) =>
    new Observable<T>((subscriber) =>
      source.subscribe({
        next: (value) => ngZone.run(() => subscriber.next(value)),
        error: (error) => ngZone.run(() => subscriber.error(error)),
        complete: () => ngZone.run(() => subscriber.complete()),
      })
    );
}
```

2023-07-28 02:30 UTC, markostanimirovic commented on modules/store-devtools/src/extension.ts
> +    private ngZone: NgZone
```suggestion
    private dispatcher: DevtoolsDispatcher
```

Add private class member:

```ts
private zoneConfig: ZoneConfig;
```

in the constructor:

```ts
this.zoneConfig = injectZoneConfig(config.connectInZone);
```

2023-07-28 02:30 UTC, markostanimirovic commented on modules/store-devtools/src/extension.ts
> +
```suggestion
```

2023-07-28 02:30 UTC, markostanimirovic commented on modules/store-devtools/src/extension.ts
> +          );
```suggestion
      const connection = this.zoneConfig.connectInZone
        ? this.devtoolsExtension.connect(this.getExtensionConfig(this.config))
        : this.zoneConfig.ngZone.runOutsideAngular(() =>
            this.devtoolsExtension.connect(this.getExtensionConfig(this.config))
          );
```

2023-07-28 09:34 UTC, timdeschryver commented on modules/store-devtools/src/config.ts
> +  ngZone?: 'enabled' | 'noop';
I see why this cannot be very clear, and I agree that we should change it.
However, I don't really like to have a default value of `true` for a boolean.

What about the following?

```ts
(extension)ConnectionType?: 'ngZone' (default) | 'runOutsideAngular'
```

2023-07-28 11:26 UTC, markostanimirovic commented on modules/store-devtools/src/config.ts
> +  ngZone?: 'enabled' | 'noop';
What about `connectOutsideZone` that would be `false` by default? 👀 

cc @brandonroberts @arturovt

2023-07-28 12:25 UTC, timdeschryver commented on modules/store-devtools/src/config.ts
> +  ngZone?: 'enabled' | 'noop';
That's good for me 👍

2023-07-28 12:39 UTC, brandonroberts commented on modules/store-devtools/src/config.ts
> +  ngZone?: 'enabled' | 'noop';
Seems reasonable to me

2023-07-28 16:02 UTC, markostanimirovic approved these changes
LGTM 👍 Thanks @arturovt!

2023-07-28 16:03 UTC, merged

2023-07-28 17:07 UTC, timdeschryver commented
Thanks @arturovt !

2023-10-23 18:38 UTC, alex-okrushko commented
Thanks for the fix @arturovt !
I ran into this issue myself, and when debugging I noticed it led back to ngrx/store-devtools 😱

@brandonroberts @markostanimirovic @timdeschryver I think it would make sense to have `runOutsideAngular` be enabled by default. I know it's a "change in behavior" but it's fixing something that should not have been there to begin with - app shouldn't rely on arbitrary change detection triggers outside of the app.

2023-10-23 18:46 UTC, brandonroberts commented
> Thanks for the fix @arturovt ! I ran into this issue myself, and when debugging I noticed it led back to ngrx/store-devtools 😱
> 
> @brandonroberts @markostanimirovic @timdeschryver I think it would make sense to have `runOutsideAngular` be enabled by default. I know it's a "change in behavior" but it's fixing something that should not have been there to begin with - app shouldn't rely on arbitrary change detection triggers outside of the app.

Agreed. We can possibly land this change as part of the 17.x release and do a migration for existing apps also to keep the current behavior.

2023-10-23 23:04 UTC, markostanimirovic commented
> Thanks for the fix @arturovt ! I ran into this issue myself, and when debugging I noticed it led back to ngrx/store-devtools 😱
> 
> @brandonroberts @markostanimirovic @timdeschryver I think it would make sense to have `runOutsideAngular` be enabled by default. I know it's a "change in behavior" but it's fixing something that should not have been there to begin with - app shouldn't rely on arbitrary change detection triggers outside of the app.

Sounds good to me 👍