feat(data): standalone support for ng add @ngrx/data
ngrx/platform pull request #4019
Opened 2023-08-29 15:51 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently ng add do not have standalone for @ngrx/data package

Closes #3935 

Add standalone configuration support for ng add command for @ngrx/data package

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2023-09-13 22:48 UTC, brandonroberts commented
Thanks @va-stefanek. The snapshot test should be committed also to fix the failing test

2023-09-16 20:02 UTC, va-stefanek commented
@brandonroberts done :)

2023-09-17 17:24 UTC, brandonroberts approved these changes

2023-09-17 19:59 UTC, markostanimirovic requested changes

2023-09-17 19:59 UTC, markostanimirovic commented on modules/data/schematics/ng-add/__snapshots__/index.spec.ts.snap
> +  providers: [provideEntityData(withEffects())]
The `provideEntityData` function expects `entityConfig` as the required argument. Check the function signature here: https://github.com/ngrx/platform/blob/main/modules/data/src/provide-entity-data.ts#L240

If the `entityConfig` option is `false`, we can pass an empty object:

```ts
  providers: [provideEntityData({}, withEffects())],
```

2023-09-17 19:59 UTC, markostanimirovic commented on modules/data/schematics/ng-add/__snapshots__/index.spec.ts.snap
> +  providers: [provideEntityData(withEffects(), entityConfig)]
`entityConfig` should be the first argument:

```ts
  providers: [provideEntityData(entityConfig, withEffects())]
```

2023-09-17 21:51 UTC, markostanimirovic approved these changes

2023-09-17 21:52 UTC, merged