feat(devtools): add simple documentation for connectOutsideZone config option
ngrx/platform pull request #4048
Opened 2023-09-18 14:41 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

Closes #4008 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2023-09-18 14:43 UTC, va-stefanek commented
@markostanimirovic I have added simple documentation based on the comments in code and issues in scope of which that config field has been added. If I miss something important in scope of the functionality it applies, please correct me.

2023-09-18 15:01 UTC, markostanimirovic requested changes

2023-09-18 15:13 UTC, va-stefanek commented on projects/ngrx.io/content/guide/store-devtools/index.md
> +      connectOutsideZone: true // If set to true, the connection with dev tools extension will be estabilished in scope Angular zone
Wow, I totally confused this even though the name suggested the exact opposite 🤕

2023-09-18 15:19 UTC, markostanimirovic commented on projects/ngrx.io/content/guide/store-devtools/index.md
> +      connectOutsideZone: true // If set to true, the connection with dev tools extension will be estabilished in scope Angular zone
Btw, you don't need to squash commits before push. It's easier for us to track requested changes when they are pushed as a separate commit.

2023-09-20 16:42 UTC, timdeschryver approved these changes
✨

2023-09-20 16:42 UTC, merged