refactor(example-app): use create action group function for actions
ngrx/platform pull request #4239
Opened 2024-02-11 00:35 UTC by jovanmit998

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`createAction` function is used for creating actions

Closes #

## What is the new behavior?
Switch to the `createActionGroup` function for a cleaner code in action files
## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2024-02-11 20:40 UTC, markostanimirovic requested changes

2024-02-11 20:40 UTC, markostanimirovic commented on projects/example-app/src/app/auth/actions/index.ts
>  export { AuthActions, AuthApiActions, LoginPageActions };
Let's remove barrel files for actions. With `createActionGroup`, they are not needed anymore.

2024-02-11 20:40 UTC, markostanimirovic commented on projects/example-app/src/app/books/actions/index.ts
> +import { viewBookPageActions as ViewBookPageActions } from './view-book-page.actions';
same here

2024-02-11 20:40 UTC, markostanimirovic commented on projects/example-app/src/app/core/actions/index.ts
> +import { userActions as UserActions } from './user.actions';
here as well

2024-02-13 10:56 UTC, jovanmit998 commented
> Great work! Can you rename action groups to use `PascalCase` instead of `camelCase`? This should greatly reduce the number of changed lines and is also the preferred way of naming action groups in our [official docs](https://ngrx.io/guide/store/action-groups).

Thank you for the review and the comments 🙇 , will switch to `PascalCase`
Just a small question, is there any reason for writing action groups in `PascalCase` instead of `camelCase `?

2024-02-14 15:37 UTC, markostanimirovic commented
> Thank you for the review and the comments 🙇 , will switch to `PascalCase` Just a small question, is there any reason for writing action groups in `PascalCase` instead of `camelCase `?

It's just a convention used for NgRx actions for a long time. Camel case is also fine.

Consistent naming across the project is important.

2024-02-14 15:38 UTC, markostanimirovic approved these changes

2024-02-14 17:22 UTC, timdeschryver approved these changes
Thanks @jovanmit998 !

2024-02-14 17:22 UTC, merged