docs(effects): remove concatLatestFrom section content
ngrx/platform pull request #4361
Opened 2024-05-27 12:19 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

2024-05-27 17:20 UTC, timdeschryver approved these changes

2024-05-27 17:25 UTC, timdeschryver requested changes
Since #4358 already added a note, we can also include a similar note within this PR for `concatLatestFrom`.
Let's first wait until we agree on the note.

2024-05-30 16:37 UTC, timdeschryver reviewed
@va-stefanek the v17 are up.
Can you add a note to the operators docs as well please?

Something as the following (but then for concatLatestFrom)

```html
<div class="alert is-helpful">

The `tapResponse` operator has been moved from `@ngrx/component-store` to `@ngrx/operators`. If you're looking for the older documentation (prior to v18), see the [v17 documentation](https://v17.ngrx.io/guide/component-store/effect#tapresponse).

</div>
```

2024-06-05 14:55 UTC, timdeschryver approved these changes

2024-06-05 15:53 UTC, brandonroberts approved these changes

2024-06-05 15:54 UTC, merged