docs: add v18 migration guide
ngrx/platform pull request #4378
Opened 2024-06-07 07:18 UTC by timdeschryver

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #4376

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2024-06-08 12:38 UTC, markostanimirovic approved these changes

2024-06-10 00:40 UTC, brandonroberts requested changes

2024-06-10 00:40 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v18.md
> +This change has a ng-update schematic that will automatically update your code.
```suggestion
This change has an ng-update schematic that automatically updates your code.
```

2024-06-10 00:40 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v18.md
> +This change has a ng-update schematic that will automatically update your code.
```suggestion
This change has an ng-update schematic that automatically updates your code.
```

2024-06-10 00:40 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v18.md
> +This change has a ng-update schematic that will automatically update your code.
```suggestion
This change has an ng-update schematic that automatically updates your code.
```

2024-06-10 00:40 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v18.md
> +- TypeScript version 5.x
```suggestion
- TypeScript version 5.4.x
```

2024-06-10 00:40 UTC, brandonroberts commented on projects/ngrx.io/content/guide/migration/v18.md
> +NgRx supports using the Angular CLI `ng update` command to update your dependencies. Migration schematics are run to make the upgrade smoother. These schematics will fix some of the breaking changes.
```suggestion
NgRx supports using the Angular CLI `ng update` command to update your dependencies. Migration schematics are run to make the upgrade smoother. These schematics fix some of the breaking changes.
```

2024-06-10 05:58 UTC, timdeschryver commented
Thanks @brandonroberts !

2024-06-10 13:18 UTC, brandonroberts approved these changes
🚀

2024-06-10 13:18 UTC, merged