feat(entity): strengthen typing of getInitialState to catch invalid a…
ngrx/platform pull request #4423
Opened 2024-07-14 02:36 UTC by GavynHolt

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

When initializing an `EntityAdapter<T>` and subsequently setting the `initialState` using `...adapter.getInitialState({ <additional state here>})`, it is possible, given the current interface, to introduce unknown variables that do not conform to the user's specified state. This could result in bugs related to mistyped variable names, resulting in confusing user error scenarios.

Closes #4422

## What is the new behavior?

This small change modifies the interface to require that the input state `S` extends `EntityState<T>`, requires that the additionalState `state` argument conforms to an Omit version of this `S` type, which removes the 'id' and 'entities' properties by way of `keyof EntityState<T>`, and then finally, since the argument now already extends `EntityState<T>`, we can now simply return `S`.

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

I have answered "Yes", but realistically, if a user of the Entity package has entered in correct code already, there will be no breaking changes. Any breaking changes should be in the form of a user now being aware of incompatible property types in their additional state, or if their State interface does not contain `extends EntityState<T>`.

## Other information

This change has helped my place of employment from unknown state properties quite nicely, but I must say this is my very first community/open source pull request. I would be happy to take any constructive criticism or guidance on anything that I could do better here. Very excited to be contributing and hope this is of help. 

Thank you, -Gavyn Holt

2024-07-16 17:40 UTC, timdeschryver reviewed
Thanks for the PR @GavynHolt .
Imho this is a useful change, but we cannot merge this now because this is a breaking change. I'll leave this open as we can revisit this on our next major version release.

2024-07-16 17:41 UTC, timdeschryver requested changes
Wanted to mention the above comment as a request for changes to prevent an accidental merge.

2024-07-17 01:02 UTC, brandonroberts commented
I think we should close this PR and revisit closer to the v19 release cycle for breaking changes

2024-07-17 17:18 UTC, timdeschryver commented
> I think we should close this PR and revisit closer to the v19 release cycle for breaking changes

Sounds good!

2024-07-17 17:18 UTC, closed without merging